"use client";

import Link from "next/link";
import { Database, Download, KeyRound, PlugZap, ShieldCheck, TestTube2 } from "lucide-react";
import { ActionModal, Badge, Card, EmptyState, Field, Input, PageHeader, TableShell } from "@/components/ui";
import { saveIntellyDteConfigAction, testIntellyDteConfigAction } from "@/features/integrations/actions";
import { getStatusLabel } from "@/lib/presentation";

type Attempt = { id: string; createdAt: string; operation: string; status: string; correlationId: string; safeMessage: string | null };

export function IntegrationManager({ dbOk, dte, config, attempts }: { dbOk: boolean; dte: { ok: boolean; safeMessage: string }; config: { baseUrl: string; configured: boolean; apiKeyMask: string; updatedAt: string | null }; attempts: Attempt[] }) {
  const actions = <><ActionModal triggerLabel="Configurar IntellyDTE" triggerIcon={<KeyRound size={18} />} title="Configurar IntellyDTE" description="La API Key se cifra antes de guardarse y nunca vuelve a mostrarse completa." submitLabel="Guardar configuración" action={saveIntellyDteConfigAction}>{(state) => <><Field label="Base URL" error={state.fieldErrors?.baseUrl?.[0]}><Input required type="url" name="baseUrl" defaultValue={config.baseUrl} placeholder="https://api.intellydte.cl/v1" /></Field><Field label="API Key" error={state.fieldErrors?.apiKey?.[0]} hint={config.configured ? `Configurada como ${config.apiKeyMask}. Déjala vacía para conservarla.` : "Solicítala en IntellyDTE."}><Input name="apiKey" type="password" autoComplete="off" placeholder={config.configured ? "Conservar API Key actual" : "Pega aquí la API Key"} /></Field></>}</ActionModal>{config.configured ? <ActionModal triggerLabel="Probar conexión" triggerIcon={<TestTube2 size={18} />} variant="secondary" title="Probar conexión" description="Se verificará la Base URL sin emitir documentos." submitLabel="Iniciar prueba" action={testIntellyDteConfigAction}>{() => <p className="text-sm text-[var(--color-muted-foreground)]">La prueba puede tardar algunos segundos y no modifica facturas.</p>}</ActionModal> : null}<Link href="/api/export/integraciones" className="btn-secondary"><Download size={18} />Exportar historial</Link></>;
  return <div className="space-y-6">
    <PageHeader title="Integraciones" description="Configura IntellyDTE y revisa su trazabilidad sin exponer credenciales." action={actions} />
    <section className="grid gap-4 md:grid-cols-2">
      <Card className="brand-card"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[rgb(47_167_255_/_0.1)] text-[var(--brand-royal)]"><Database /></div><div><h2 className="font-bold text-[var(--brand-deep)]">MySQL</h2><p className="text-sm text-[var(--color-muted-foreground)]">Pool de persistencia</p></div></div><Badge status={dbOk ? "paid" : "rejected"}>{dbOk ? "Operativo" : "No disponible"}</Badge></div></Card>
      <Card className="brand-card"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[rgb(20_208_246_/_0.1)] text-[var(--brand-navy)]"><PlugZap /></div><div><h2 className="font-bold text-[var(--brand-deep)]">IntellyDTE</h2><p className="text-sm text-[var(--color-muted-foreground)]">{dte.safeMessage}</p>{config.configured ? <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{config.apiKeyMask}</p> : null}</div></div><Badge status={dte.ok ? "paid" : "pending"}>{dte.ok ? "Operativo" : config.configured ? "Revisar" : "Sin configurar"}</Badge></div></Card>
    </section>
    <Card className="min-w-0"><div className="mb-5 flex items-center gap-2 text-[var(--brand-royal)]"><ShieldCheck size={20} /><h2 className="text-lg font-bold text-[var(--brand-deep)]">Actividad de integración</h2></div>{attempts.length ? <TableShell><thead><tr><th>Fecha</th><th>Operación</th><th>Estado</th><th>Correlación</th><th>Mensaje seguro</th></tr></thead><tbody>{attempts.map((attempt) => <tr key={attempt.id}><td>{new Date(attempt.createdAt).toLocaleString("es-CL")}</td><td>{attempt.operation}</td><td><Badge status={attempt.status}>{getStatusLabel(attempt.status)}</Badge></td><td className="font-mono text-xs">{attempt.correlationId}</td><td>{attempt.safeMessage ?? "—"}</td></tr>)}</tbody></TableShell> : <EmptyState title="Sin actividad externa" copy="Los intentos de emisión aparecerán aquí con información redactada." />}</Card>
  </div>;
}
