"use client";

import { Download, FileDown, FileText, ReceiptText, RefreshCw, Upload } from "lucide-react";
import { ActionModal, Badge, Card, EmptyState, Field, IconButton, Input, PageHeader, Pagination, TableShell, TableToolbar } from "@/components/ui";
import { importHistoricalInvoicesAction, issueInvoiceAction, refreshInvoiceStatusAction } from "@/features/billing/actions";
import { formatClpAmount } from "@/lib/money";
import { getStatusLabel } from "@/lib/presentation";
import type { PageQuery } from "@/lib/list-query";

type InvoiceItem = { id: string; orderNumber: string; clientName: string; total: string; status: string; folio: string | null; siiStatus: string | null; siiGlosa: string | null; hasPdf: boolean; hasXml: boolean };
type ReadyOrder = { id: string; number: string; clientName: string; total: string };

export function BillingManager({ items, ready, canImport, query, page, pageSize, total }: { items: InvoiceItem[]; ready: ReadyOrder[]; canImport: boolean; query: PageQuery; page: number; pageSize: number; total: number }) {
  const actions = <>{canImport ? <ActionModal iconOnly triggerLabel="Importar facturas históricas" triggerIcon={<Upload size={18} />} variant="secondary" title="Importar facturas históricas" description="Sólo acepta documentos emitidos vinculados a órdenes pagadas." submitLabel="Importar facturas" action={importHistoricalInvoicesAction}>{() => <Field label="Archivo CSV" hint="Folio e ID externo son obligatorios."><Input required name="file" type="file" accept=".csv,text/csv" /></Field>}</ActionModal> : null}<IconButton href="/api/export/facturacion" label="Exportar facturación" icon={<Download size={18} />} /><IconButton href="/api/export/facturacion?template=1" label="Descargar plantilla de facturación" icon={<FileDown size={18} />} /></>;
  return <div className="space-y-6">
    <PageHeader title="Facturación" description="Emite una factura por orden pagada y revisa el resultado normalizado de IntellyDTE." action={actions} />
    {ready.length ? <Card className="brand-card"><h2 className="mb-5 text-lg font-bold text-[var(--brand-deep)]">Listas para facturar</h2><div className="grid gap-3">{ready.map((order) => <div key={order.id} className="flex flex-col justify-between gap-4 rounded-[var(--radius-md)] border border-[var(--color-border)] bg-[var(--color-background-soft)] p-4 sm:flex-row sm:items-center"><div><p className="font-mono text-xs text-[var(--color-muted-foreground)]">{order.number}</p><p className="mt-1 font-semibold text-[var(--brand-deep)]">{order.clientName}</p><p className="mt-1 text-sm text-[var(--color-muted-foreground)]">{formatClpAmount(Number(order.total))}</p></div><ActionModal iconOnly triggerLabel="Emitir factura" triggerIcon={<ReceiptText size={16} />} title="Emitir factura" description="Se enviará la orden pagada a IntellyDTE." submitLabel="Confirmar emisión" pendingLabel="Emitiendo factura…" action={issueInvoiceAction}>{() => <><input type="hidden" name="orderId" value={order.id} /><p className="text-sm text-[var(--color-muted-foreground)]">Confirma la facturación de <strong>{order.number}</strong> por <strong>{formatClpAmount(Number(order.total))}</strong>.</p></>}</ActionModal></div>)}</div></Card> : null}
     <TableToolbar query={query} tabs={[{ value: "all", label: "Todas" }, { value: "pending", label: "Pendientes" }, { value: "processing", label: "Procesando" }, { value: "issued", label: "Emitidas" }, { value: "rejected", label: "Rechazadas" }]} />
     <form method="get" className="flex flex-wrap items-end gap-3" aria-label="Filtros por fecha"><input type="hidden" name="q" value={typeof query.q === "string" ? query.q : ""} /><input type="hidden" name="status" value={typeof query.status === "string" ? query.status : ""} /><input type="hidden" name="tab" value={typeof query.tab === "string" ? query.tab : ""} /><label className="grid gap-1 text-sm font-semibold text-[var(--brand-deep)]">Desde<input className="field" type="date" name="from" defaultValue={typeof query.from === "string" ? query.from : ""} /></label><label className="grid gap-1 text-sm font-semibold text-[var(--brand-deep)]">Hasta<input className="field" type="date" name="to" defaultValue={typeof query.to === "string" ? query.to : ""} /></label><button className="btn-secondary" type="submit">Aplicar fechas</button></form>
     <section className="min-w-0 space-y-4"><h2 className="text-lg font-bold text-[var(--brand-deep)]">Documentos</h2>{items.length ? <TableShell mobileCards><thead><tr><th>Orden</th><th>Cliente</th><th>Estado</th><th>Folio</th><th className="text-right">Total</th><th className="text-right">Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td data-label="Orden" className="font-mono text-xs">{item.orderNumber}</td><td data-label="Cliente" className="font-medium">{item.clientName}</td><td data-label="Estado"><Badge status={item.status}>{getStatusLabel(item.status)}</Badge>{item.siiGlosa ? <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">{item.siiGlosa}</p> : item.siiStatus ? <p className="mt-1 text-xs text-[var(--color-muted-foreground)]">SII: {item.siiStatus}</p> : null}</td><td data-label="Folio">{item.folio ?? "—"}</td><td data-label="Total" className="text-right font-semibold">{formatClpAmount(Number(item.total))}</td><td data-label="Acciones" className="flex justify-end gap-2">{item.status !== "issued" || !item.hasPdf ? <ActionModal iconOnly triggerLabel="Actualizar estado fiscal" triggerIcon={<RefreshCw size={17} />} title="Actualizar estado fiscal" description="Se consultará IntellyDTE sin volver a emitir la factura." submitLabel="Consultar estado" action={refreshInvoiceStatusAction}>{() => <input type="hidden" name="invoiceId" value={item.id} />}</ActionModal> : null}{item.status === "issued" && item.hasPdf ? <IconButton href={`/api/invoices/${item.id}/pdf`} label="Descargar PDF fiscal" icon={<FileDown size={17} />} /> : null}{item.status === "issued" && item.hasXml ? <IconButton href={`/api/invoices/${item.id}/xml`} label="Descargar XML firmado" icon={<FileText size={17} />} /> : null}</td></tr>)}</tbody></TableShell> : <EmptyState title="Aún no hay facturas" copy="Las órdenes pagadas aparecerán aquí listas para emitir." />}</section>
    <Pagination page={page} pageSize={pageSize} total={total} query={query} />
  </div>;
}
